### PR TITLE
SERVER-16685 use buildInfo over 32bit check for WT

### PR DESCRIPTION
**Pull request by jameswahlin**
An earlier commit on this ticket added a storageEngine list to buildInfo. This commit changes a jstest that was previously using a "32 bit build" check for WT exclusion to now use buildInfo to confirm inclusion.

### CODE REVIEW

**Comment by milkie** [comment]
There are multiple tests that use the 32-bit check to avoid failures on WiredTiger.  Should we change them all?

**Comment by jameswahlin** [comment]
@milkie - can you point me towards the other tests or provide guidance on how to find? This was the one that I found that was clearly using the 32bit buildInfo check as a proxy for WiredTiger inclusion.

**Comment by milkie** [comment]
There are some tests that need wiredTiger actively running, but sharding_system_namespaces.js is not one of them.  This particular test is special in that it only needs wiredTiger support compiled in, to validate storage engine options.
This pull request is complete and there is nothing further to do with the other tests.  Thanks to James for clearing this up.

**Comment by jameswahlin** [comment]
Closed as I now have permission to push directly.

**Pull request closed without merging**
