### PR TITLE
SERVER-62595: Collate and update logging documentation

### PR DESCRIPTION
**Pull request by agolin95**
Initial draft PR migrates the logv2 README to newly created docs/logging.md.

We still need to incorporate the [Log Severity Selection Policy ](https://wiki.corp.mongodb.com/display/COREENG/Log+Severity+Selection+Policy), but I'd like to get a technical expert to review that content for staleness and make suggestions about rolling it into logging.md.

After we integrate the selection policy, the technical expert should do a general pass through logging.md to ensure it is adequately up to date.

### CODE REVIEW

**Comment by BillyDonahue** [comment]
Hi. I'm glad someone's finally doing this! Let's do the move (without edits) as a single commit, so Git can track the history of the file more reliably in the master branch.  It will be necessary to find all the hyperlinks to logv2/README.md in the codebase (I think there are a few) and refresh them.

**Comment by agolin95** [comment]
Hi @BillyDonahue thank you for weighing in! I just added a commit that updates the references in logging.h, which were the only ones I was able to turn up by searching for "logv2/readme".

Assuming there are no other dangling stale references, sounds like the best way to proceed would be to squash and merge this PR and follow up with any collation and edits in a subsequent PR, correct?

**Comment by BillyDonahue** [comment]
> Hi @BillyDonahue thank you for weighing in! I just added a commit that updates the references in logging.h, which were the only ones I was able to turn up by searching for "logv2/readme".
> 
> Assuming there are no other dangling stale references, sounds like the best way to proceed would be to squash and merge this PR and follow up with any collation and edits in a subsequent PR, correct?

That makes sense to me, yeah.

**Review by BillyDonahue — APPROVED** [review]

**Comment by agolin95** [comment]
New to the server contribution process and did not realize I should have targeted the 10gen repo, opening a new PR there!

**Pull request closed without merging**
