### PR TITLE
Fix typo in example output on mongotop man page

### PR DESCRIPTION
**Pull request by ebcagadas**
Example output shows mongotop reporting every 15 minutes instead of 15 seconds.

### CODE REVIEW

**Comment by Schubes** [comment]
Hi @ebcagadas,

Thanks for the pull request. Would you please sign our [contributor's agreement](http://www.mongodb.com/contributor)? Once the agreement has been signed, I'd be happy to create a [SERVER](https://jira.mongodb.org/projects/SERVER/issues/) jira ticket on your behalf to track this change.

Kind regards,
Kelsey

**Comment by ebcagadas** [comment]
Done signing the contributor's agreement.

**Comment by Schubes** [comment]
Thank you for your contribution, @ebcagadas! I've noted that our documentation contains the same typo and flagged it while resolving [SERVER-32234](https://jira.mongodb.org/browse/SERVER-32234). Please feel free to open a pull request against https://github.com/mongodb/docs/blob/master/source/reference/program/mongotop.txt if you would like to correct this issue in our documentation as well.

Kind regards,
Kelsey

**Comment by ebcagadas** [comment]
My apologies @Schubes for not being able to check the docs repo for the same typo that I have corrected. Good thing @kay-kim has already addressed on his [commit](https://github.com/mongodb/docs/commit/a5585a70562b1b1f38cfbddc51942f774e1f46dc).

Cheers!
Emmanuel

**Comment by Schubes** [comment]
Ah, yes, she is pretty quick. Thanks again for pull request and bringing the error to our attention.

**Pull request closed without merging**
