### PR TITLE
SERVER-74191 Add flamegraph repo to system_perf.yml

### PR DESCRIPTION
**Pull request by SimonEismann**
see title, is related to [PERF-3729](https://jira.mongodb.org/browse/PERF-3729)

### CODE REVIEW

**Review by jimoleary — COMMENTED** [review]
Changes look good, but I am completely paranoid so can we have a simple smoke test patch?

**Review by jimoleary — APPROVED** [review]
LGTM based on a working patch.

**Comment by SimonEismann** [comment]
Links to the working patches:
https://spruce.mongodb.com/version/63f368b59ccd4e1e13f10af4
https://spruce.mongodb.com/version/63f368a1d1fe0763ae312b60

**Comment by SimonEismann** [comment]
evergreen merge

**Comment by SimonEismann** [comment]
Closed as I opened this against the wrong repo

**Pull request closed without merging**
