### PR TITLE
[wip] Prevent the mongo shell from being crashed by exception when query is executed.

### PR DESCRIPTION
**Pull request by ryoqun**
Sorry fo submitting this PR while being very premature..

But I can't stand SEGVs anymore..

### CODE REVIEW

**Comment by ryoqun** [comment]
Preferably, i want the mongo shell return to the repl mode when SIGINT is received...

**Comment by ramonfm** [comment]
@ryoqun , thanks for taking the time to put together a pull request. Please see the [contributor's guide](https://github.com/mongodb/mongo/blob/411e9810075556fb196278a669fab0f19ea901ce/CONTRIBUTING.rst) for information on the required steps to get this considered, including opening a JIRA ticket and signing the [contributor agreement](https://www.mongodb.com/legal/contributor-agreement).

Thanks,
Ramón.

**Comment by ramnes** [comment]
Yeah, that would be nice that a SIGV during an op kills the op rather than the shell (leaving the op running).

**Comment by charsyam** [comment]
@ryoqun How about removing two printf line?

**Comment by ryoqun** [comment]
@ramonfm @ramnes @charsyam Thanks for replies.. Well, I've been extremely busy by our business these days and will be for another couple weeks...

**Comment by ryoqun** [comment]
I'm terribly sorry however I can't afford some time required to do some paper work considering relative amount of code (well, it's just 4 LINES).

So, if someone is interested in this, I want he to continue to work on this. I'm really happy with that.

Formally, I hereby declare to waive any copyright ownership or whatsoever regarding this modification. That means I intend my modification to be treated as public domain.

I don't know this declaration works (I'm not an attorney..) Sorry for my selfish attitude..

**Comment by ryoqun** [comment]
If noone pops in, I'll resume this work once my business got stable.. :)

Anyway, thanks for creating great software. We're using Mongo DB by our business of course!

**Comment by ryoqun** [comment]
Hmm, this does works when connecting to mongo 2.x, but not to mongo 3.x???

Sorry my work is incomplete..

**Comment by ramonfm** [comment]
Thanks for the update @ryoqun. I'm going to close this pull request for the time being. When you're ready to resume your work please take a look at the [Contributor Guide](https://github.com/mongodb/mongo/blob/master/CONTRIBUTING.rst) for details on how to proceed.

**Pull request closed without merging**
