### PR TITLE
Renaming MongoDB to MerizoDB

### PR DESCRIPTION
**Pull request by sc250024**
## Description
Quite simply, this PR renames the project from **MongoDB** to **MerizoDB** in all filenames and code references.

I'm fully aware this PR will probably take the better part of a year to merge. I don't mind keeping up with the merge conflicts that will ultimately arise.

## Motivation and Context
Essentially, this came down to an email exchange between myself, and a MongoDB Consultant named Ayan. I described how I thought the project name **MongoDB** was a bit silly given the meaning of the word in English. From UrbanDictionary => https://www.urbandictionary.com/define.php?term=Mongo

### The name "Mongo" is ambiguous, and not in any way that is positive

In short, these are the meanings of the word "mongo" in English:

1. _Derogatory. Someone who suffers from Down's Syndrome (trisomy 21). Derived from contraction of a now unused description: "Mongoloid features" referring to the bridgeless nose and epicanthic folds of certain far-eastern races._

2. _In skateboarding, pushing the skateboard with your front foot. If you're normal, you use your left foot, and vice versa for goofy._

3. _Mongo as in "humongous". Used to describe something extremely large or important._

None of those descriptions are particularly interesting when it comes to databases. I'm sure the creators went for **Mongo** because they wanted to imply that their database could handle large datasets. But calling your database "large" is strange; all databases can be large, potentially. Which brings me to my next point...

### Marketing your database as "huge" is the Coors Light of advertising strategies

Check out these two Coors Light advertisements:

=> [Coors Light // Commercial // Jean-Claude Van Damme](https://www.youtube.com/watch?v=i0JJWL6zlL0)
=> [Coors Light Never Stops Commercial](https://www.youtube.com/watch?v=o0Rbzke1-Zk)

You'll notice that Coors Light goes for a very strange branding strategy: that their beer is the **coldest** you've ever tasted. Notice how they don't talk about **flavor**, or **quality**, or **craftsmanship**. No! They only claim that their beer is ice cold, like the Rocky Mountains (or your mountain range de jour).

This is quite possible the worst marketing strategy ever, and MongoDB is following a similar path. Notice how the name "Mongo", ignoring the offensive meanings, only implies that your database will be **YUUUUGGEEEE**, not fast, or scalable, or stable, or distributed. Just **huge**.

Don't be like Coors Light; market your database with a name that implies what it really does, which is act as a distributed document store. Which brings me to the next point...

### The name should be Greek, and imply a "distributed" meaning

This brings me to the new name chosen for this project: **MerizoDB**. This comes from the Greek word **"μεριζω"**, which is the Biblical Greek (yay Jesus!) for "distributed." This falls in line better with what MongoDB does. And also, like many open-source projects (Kubernetes, Istio, Prometheus, Spinnaker, etc.), it follows the naming convention that the software should come from a Greek word.

I verified this translation with my Greek roommate Evanthia. She is from Crete, and works in marketing, so the translation holds.

## How Has This Been Tested?

It hasn't yet, but considering this is just a text / file rename, no new functionality testing should be needed.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Company name change (you will need a complete restructuring of the MongoDB organization)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [ ] MongoDB marketing department is on-board with the name change

### CODE REVIEW

**Comment by markbigler** [comment]
Late April fool's joke...? 😮

**Comment by sc250024** [comment]
@markbigler Nope

**Comment by Schubes** [comment]
Hi @sc250024,

Thanks for your interest in MongoDB. We do not intend to make the change that you suggest, so I'm going to close this pull request.

Kind regards,
Kelsey

**Comment by amcgregor** [comment]
As a point to give perspective on the hilarity of this type of issue/patch from where I'm sitting, beyond it being unnecessarily pedantic in a similar vein to "master/slave" terminology push-back… (my dictionary only has "a monetary unit of Mongolia equal to one hundredth of a tugrik"…)

I have a bit shy of **50 TB** of data (<i>tera</i>bytes) in MongoDB at this point, containing pretty much _everything_ digital I have touched since 2001, plus the latest Wipedia/media extracts, plus Project Gutenberg, plus most of StackExchange, plus enough music to run a radio station for 57 _days_ straight without a repeat, … "humongous" is a perfectly appropriate reference, given it _really can_ handle humongous amounts of data, though, true, not everyone _has_ humongous amounts of data.

This dataset took three months—continuously—to offsite backup after my last move, and would cost ~half a million dollars per month if restructured to host on Amazon S3. As it is, I've had to shovel three replacement drives into my at-home arrays in the last 8 years—almost _infinitely_ more cost effective.  Thanks MongoDB GridFS!

(I still get giggles every time I re-read "you will need a complete restructuring of the MongoDB organization". So, thank you for this existing. Sincerely. The irony of so casually demanding an astonishingly humungous amount of additional, expensive work for a "such a simple change" is palpable.)

:sips her Coors, then remembers she drinks Guinness, yuck:

**Comment by sc250024** [comment]
@amcgregor Thank you for the lovely comment! You're right, this pull request was 50% 'pedantic in a similar vein to "master/slave" terminology push-back', but also 50% genuine interest in changing the name of this project. I have always thought the name of the MongoDB project was a bit silly; to me, the term 'mongo' sounds like something a Jeff Spicoli-type would say (I have nothing against Jeff Spicoli-types, by the way). However, [choosing names for things is always hard](https://martinfowler.com/bliki/TwoHardThings.html), so go figure.

The truth is I was in a silly mood myself after arguing with my Greek roommate Eva about the roots of various English words. I explained to her (she works in marketing) that many projects in the cloud computing era have Greek names, and having my previous opinions on MongoDB, had her help me select a better name for this project using a Greek name. The Coors Light logic is separate, but still relevant. Seriously, who markets their freaking beer as the *coldest* !?

Thanks to @amcgregor and everyone else for having a sense of humor! 😄

**Pull request closed without merging**
