### PR TITLE
Server 15793 Storage engine's updateRecord function should take oldRec

### PR DESCRIPTION
**Pull request by gevorgvoskanyan**
This is a new pull request for https://jira.mongodb.org/browse/SERVER-15793. The original one - #837, was recently closed due to merge conflicts. This one is based on a newer commit by @esmet : https://github.com/Tokutek/tokumxse/commit/6ce943fc1bb7994d68524d4fb8956a7cd46290ad, and an top of it adds changes to RocksDB and WiredTiger storage engines to take advantage of the passed-in old record.
Many thanks to John Esmet who authored the bulk of the changes in this pull request!

### CODE REVIEW

**Comment by benmccann** [comment]
@igorcanadi @siying you guys might be interested in this RocksDB PR as well since it should give a good performance improvement

**Comment by igorcanadi** [comment]
Yup, definitely sounds interesting, thanks @benmccann

**Comment by benmccann** [comment]
@benety any thoughts on this one? i'd really love to try it out with 2.8.0-RC6 since it seems like such a massive performance improvement to RocksDB

**Comment by igorcanadi** [comment]
@benmccann are you testing performance of Mongo+Rocks?

**Comment by benmccann** [comment]
@igorcanadi i was thinking about it. i just did a mongoexport of a large amount of data from our DB and was planning to do some benchmarking and stability testing at least with mmap & wiredtiger for the new 2.8 storage engine stuff. i really wanted to include mongo+rocks as well if we could get this change in. figured it'd be better to do after the change than before given how big of a difference it looks like it will make. btw, we can make this same change with rocks delete functionality it looks like. figured we could send a PR for that as well, but wanted to make sure this was well-received first

**Comment by igorcanadi** [comment]
There is bunch more perf improvements coming to mongo+rocks, but it would be definitely interesting to get current numbers. We will change disk format regularly, though, sorry about that :)

**Comment by benmccann** [comment]
@igorcanadi no problem. I know it's only an RC right now. Are your other perf improvements going to make it in for 2.8 you think? I'd be curious if you guys test this change out at all

**Comment by benety** [comment]
Thank you for your submission. I appreciate that the patch simplifies RecordStore::updateRecord() and, in the case of RocksDB, eliminates another error status that the client has to handle.

However, due to scheduling constraints and other 3.0 priorities, I'm not confident that we can get this in for 3.0 [BTW, the upcoming release is no longer called 2.8.](http://www.mongodb.com/blog/post/renaming-our-upcoming-release-mongodb-30).

@gevorgvoskanyan, I would prefer that @esmet submit the pull request for the interface change (post 3.0). Once that's in, you can submit a pull request for your changes to the individual record stores.

@benmccann, if you have performance numbers supporting the change in the interface, please feel free to post them in [SERVER-15793](https://jira.mongodb.org/browse/SERVER-15793). You will get a lot more visibility for your findings there.

Closing this pull request.

**Comment by benmccann** [comment]
I've finally had time to benchmark this change. It's about a 30% speedup for RocksDB. Posted numbers on the issue: https://jira.mongodb.org/browse/SERVER-15793

**Pull request closed without merging**
