### PR TITLE
SERVER-23108: shell features - db.grep() and db.collection.fields()

### PR DESCRIPTION
**Pull request by blowhacker**
db.grep() -> adds a shell function to objects in all indexed fields across all collections in a database

db.collection.fields() -> lists fields in a collection

### CODE REVIEW

**Comment by monkey101** [comment]
this was closed by accident

**Comment by ramonfm** [comment]
Hi @blowhacker, apologies for the long delay in getting back to you. I can't find a JIRA ticket for this PR, have you opened one? If not, please [open a ticket in the SERVER project](https://jira.mongodb.org).

When you open the JIRA ticket, please clarify what's the use case this pull request is trying to address. Also since you opened this PR MongoDB has added the [$sample operator](https://docs.mongodb.org/manual/reference/operator/aggregation/sample/), which I wonder if it meets some of your needs.

Thanks,
Ramón.

**Comment by blowhacker** [comment]
@ramonfm thanks for your reply. I never created a JIRA. 
$sample might be useful for the fields() feature.

Let me create new pull requests off the latest master and create a JIRA -- I didn't know  a JIRA was necessary.

**Comment by ramonfm** [comment]
Closing as per https://jira.mongodb.org/browse/SERVER-23108

**Pull request closed without merging**
