### PR TITLE
SERVER-43926 fix typo in error message

### PR DESCRIPTION
**Pull request by terencehonles**

### CODE REVIEW

**Comment by dhatcher42** [comment]
Thanks for making this Pull Request! Even for small items like this we require signing of our [Contributor's Agreement|https://www.mongodb.com/legal/contributor-agreement] before we can accept the PR. Could you please do so?

**Comment by dhatcher42** [comment]
@terencehonles as a reminder, if you'd like us to accept this Pull Request we will need you to sign our [Contributor Agreement](https://www.mongodb.com/legal/contributor-agreement).

**Comment by terencehonles** [comment]
@dhatcher42 signed

**Comment by edzh** [comment]
Hi @terencehonles, it appears that after some time, this issue was picked up independent of this pull request, see: [SERVER-57560](https://jira.mongodb.org/browse/SERVER-57560). I'll now close this pull request since it's been resolved.

Nevertheless, we appreciate your contribution and participation in helping to improve MongoDB, and look forward to your future pull requests.

**Comment by terencehonles** [comment]
@edzh thanks, at least someone got it, but hopefully PRs don't get abandoned like this since that likely created extra work for someone else. I'm not sure why it took me as long as it did to sign the CLA (or possibly notice the comment), but that obviously didn't help...

**Pull request closed without merging**
