### PR TITLE
SERVER-5399 Essentially aliasing quit, exit, and function call variations. (+ misc cleanup)

### PR DESCRIPTION
**Pull request by amcfague**
Previously, `exit` was being implemented as a code in the DB shell, while 
`quit` was being implemented as a shell function.  This meant that both were 
doing different things, and were called differently--i.e., `exit` could be run 
as is, whereas `quit()` had to be called as a function.

### CODE REVIEW

**Comment by benety** [comment]
@amcfague,

This is merged in https://github.com/mongodb/mongo/commit/f1d696d46b65dd1f76727b37d85e0c08c291f533.

Thank you for contributing to MongoDB!
Ben

**Comment by benety** [comment]
Reverted in https://github.com/mongodb/mongo/commit/fc14926f9c8256edce8bbd15d439ca34667c6ebb

See:

https://jira.mongodb.org/browse/SERVER-17167

**Comment by amcfague** [comment]
This pull request is almost 3 years old; I'm not surprised it's broken with the latest version.  I'm honestly surprised it merged cleanly at all.  I'd consider this discarded.

**Comment by benety** [comment]
There were some merge conflicts we had to resolve while rebasing this. Probably broke something while rebasing it.

**Pull request closed without merging**
