### PR TITLE
Remove debug on debian/prerm script

### PR DESCRIPTION
**Pull request by spk**
Hi,
Just deleting this `echo` debug output on Debian packaging.
Cheers

### CODE REVIEW

**Comment by ramonfm** [comment]
Thanks @spk . I forgot to ask you to sign the [contributor's agreement](https://www.mongodb.com/legal/contributor-agreement) before merging your request. I doubt this is an issue in this case but I'd appreciate if you could sign it at your earliest convenience. It certainly will be needed if you'd like to make other contributions to MongoDB.

Thanks,
Ramón.

**Comment by spk** [comment]
Hi @ramonfm, I will read it and sign no problem.
Cheers,
Laurent

**Comment by ramonfm** [comment]
Thanks @spk, much appreciated.

**Comment by spk** [comment]
Hi, its signed. Laurent

**Comment by ramonfm** [comment]
Thank you @spk.

**Pull request closed without merging**
