### PR TITLE
SERVER-58477 Minor wording changes and typo fixes in SConstruct

### PR DESCRIPTION
**Pull request by ryandesign**
This PR makes minor changes in descriptions and comments in SConstruct. It fixes typos, some punctuation, some run-on sentences, and there was some inconsistency in the descriptions of the flags and variables that I tried to resolve; hope I made the right choice.

### CODE REVIEW

**Comment by acmorrow** [comment]
Thanks @ryandesign for the PR. Given how many of these I wrote, I guess the story here is that I should figure out whatever it is that has been preventing `flyspell` from working right in my editor.

**Comment by acmorrow** [comment]
@ryandesign - A few quick things before I can merge this:

- Could you please update the commit description to have a ticket? I'm fine using SERVER-50115 for that. Running `git log` should show the proper format.
- Have you signed the https://www.mongodb.com/legal/contributor-agreement ?

Thanks,
Andrew

**Comment by ryandesign** [comment]
While I'm sure the policies you're following here are not of your own design, I have to say that I'm disappointed that my work in this PR was allowed to bitrot rather than being accepted when I submitted it.

I do not have time to follow up on every contribution I make to every project. I missed the email in which you asked me to change the commit message and sign the CLA. I rely on the developers of the projects to accept and integrate my contributions even in the absence of my continued input.

I have fixed the conflict and force-pushed the revised version.

Requiring your contributors to read, understand (possibly with the help of a lawyer), and sign a CLA is burdensome busywork. Requiring contributors to sign a CLA for obvious text typo corrections seems completely unnecessary.

The method that you have chosen for signing a CLA requires me to disable Safari's cross-site tracking prevention feature. You should not ask your contributors to do things that reduce the security of their web browser. I have signed the CLA using a different browser but you should expect other browsers to adopt more security restrictions in the future and should adjust your CLA signing mechanism accordingly.

If you require a ticket reference or other changes to my commit message, feel free to edit it. Referencing ticket SERVER-50115 makes no sense to me as that ticket is unrelated to my changes. To my knowledge no ticket exists that relates to these changes. Creating a ticket just to say "There are typos; I'll submit a PR" is more busywork.

**Comment by acmorrow** [comment]
Hi @ryandesign - 

Thanks for updating the PR. To follow-up on a few points in your note:

- You are correct that the CLA requirement is not of my design, and I can see why it seems unnecessary for something as "obvious" as typo fixes. However, I hope that you can appreciate that the lawyers of the world just don't see it that way: if we didn't always require the CLA it would become a judgment call and open the door to consequential errors. Requiring it uniformly is just safer. Note that you do only need to sign it once, so you hopefully won't need to deal with it ever again.

- I believe that the issue you encountered with needing to disable XSS mitigations in Safari has been raised before by others, but I don't remember what the outcome was. I've flagged the issue again to the internal team that manages the CLA process.

- It has been a while, but I think I suggested SERVER-50115 to you because it was part of a contemporaneous discussion, and I was actually trying to save you the need to make a busywork ticket. I agree the ticket is unrelated, so I'm sorry if that was confusing. Meanwhile, I've gone ahead and created SERVER-58477 which we will use to commit this work.

- Finally, this probably got lost in the shuffle in large part because I went on an extended period of leave shortly after my last comments above, and simply didn't remember to revisit it when I returned. On the other hand, expecting us to intuit your intentions with respect to follow-ups on the PR isn't entirely reasonable either. We can't know for a given PR which way the author would like it to be treated. If you would like to treat a future PR as fire-and-forget that's fine and we can deal with it (assuming no major changes are required), but I recommend saying so explicitly, and also accepting that such an approach somewhat lowers the likelihood that your work will get merged. For instance, it wouldn't have worked in this instance because we really did need the CLA.

I've assigned myself SERVER-58477 and will get this merged. Thanks for fixing up the typos, many of which are mine, and for contributing to MongoDB.

**Review by deriamis — APPROVED** [review]

**Pull request closed without merging**
