### PR TITLE
Changes to allow build to work with SCons 3.0. Entirely changes to print calls

### PR DESCRIPTION
**Pull request by bdbaddog**
Changes are of the form:
print "abc"
to
print("abc")

### CODE REVIEW

**Comment by acmorrow** [comment]
Thanks @bdbaddog. I'll make a ticket for this and get it applied. Is there a way to ban python2 style print calls inside python 2? In other words, to require python 3 format? Otherwise I'm worried that we will just keep re-introducing these.

**Comment by acmorrow** [comment]
I've filed https://jira.mongodb.org/browse/SERVER-30300. When I merge this, I'll amend the commit message to reference the ticket.

**Comment by acmorrow** [comment]
Changes LGTM, but I would like to know the answer to my above question before merging.

**Comment by bdbaddog** [comment]
@Schubes  already have. :) Check with @acmorrow

**Comment by bdbaddog** [comment]
@acmorrow  I think if you add 

`from __future__ import print_function`

At the top of the top level SConstruct, and (perhaps) every SConscript, that should force the issue.
And/or patch your scons-local with same. (This option would be better)

Here's the location of all such in current SCons default branch

```
src//engine/SCons/BuilderTests.py:from __future__ import print_function
src//engine/SCons/dblite.py:from __future__ import print_function
src//engine/SCons/EnvironmentTests.py:from __future__ import print_function
src//engine/SCons/Executor.py:from __future__ import print_function
src//engine/SCons/Memoize.py:from __future__ import print_function
src//engine/SCons/Node/__init__.py:from __future__ import print_function
src//engine/SCons/Node/__init__.py.orig:from __future__ import print_function
src//engine/SCons/Node/FS.py:from __future__ import print_function
src//engine/SCons/Node/FSTests.py:from __future__ import division, print_function
src//engine/SCons/Platform/__init__.py:from __future__ import print_function
src//engine/SCons/SConf.py:from __future__ import print_function
src//engine/SCons/SConsign.py:from __future__ import print_function
src//engine/SCons/Script/Interactive.py:from __future__ import print_function
src//engine/SCons/Script/Main.py:from __future__ import print_function
src//engine/SCons/Script/SConscript.py:from __future__ import print_function
src//engine/SCons/SubstTests.py:from __future__ import print_function
src//engine/SCons/Taskmaster.py:from __future__ import print_function
src//engine/SCons/Tool/cyglink.py:from __future__ import absolute_import, print_function
src//engine/SCons/Tool/DCommon.py:from __future__ import print_function
src//engine/SCons/Tool/dmd.py:from __future__ import print_function
src//engine/SCons/Tool/docbook/docbook-xsl-1.76.1/extensions/docbook.py:from __future__ import print_function
src//engine/SCons/Tool/docbook/docbook-xsl-1.76.1/extensions/xslt.py:from __future__ import print_function
src//engine/SCons/Tool/FortranCommon.py:from __future__ import print_function
src//engine/SCons/Tool/gdc.py:from __future__ import print_function
src//engine/SCons/Tool/install.py:from __future__ import print_function
src//engine/SCons/Tool/install.py.orig:from __future__ import print_function
src//engine/SCons/Tool/intelc.py:from __future__ import division, print_function
src//engine/SCons/Tool/ldc.py:from __future__ import print_function
src//engine/SCons/Tool/link.py:from __future__ import print_function
src//engine/SCons/Tool/MSCommon/common.py:from __future__ import print_function
src//engine/SCons/Tool/mslink.py:from __future__ import print_function
src//engine/SCons/Tool/msvs.py:from __future__ import print_function
src//engine/SCons/Tool/msvsTests.py:from __future__ import print_function
src//engine/SCons/Tool/qt.py:from __future__ import print_function
src//engine/SCons/Tool/rpmutils.py:from __future__ import print_function
src//engine/SCons/Tool/swig.py:from __future__ import print_function
src//engine/SCons/Tool/tex.py:from __future__ import print_function
src//script/scons-configure-cache.py:from __future__ import print_function
src//script/scons-time.py:from __future__ import division, print_function
src//script/scons.py:from __future__ import print_function
src//script/sconsign.py:from __future__ import print_function
src//setup.py:from __future__ import print_function
src//test_files.py:from __future__ import print_function
src//test_interrupts.py:from __future__ import print_function
src//test_pychecker.py:from __future__ import print_function
src//test_setup.py:from __future__ import print_function
src//test_strings.py:from __future__ import print_function
```

**Comment by acmorrow** [comment]
@bdbaddog - I'm going to merge this today. I've added `from __future__ import print_function` to the top of src/third_party/scons-2.5.0/scons-local-2.5.0/SCons/Script/SConscript.py, which seems to prevent the use of it globally.

**Comment by acmorrow** [comment]
LGTM

**Comment by acmorrow** [comment]
Merged in e9570ae0bc9dae3823ee2ef815251c02ff50e2bc

**Pull request closed without merging**
