### PR TITLE
SERVER-41641 Misspelling in uassert

### PR DESCRIPTION
**Pull request by oc666**
**too big** instead of **to big**

### CODE REVIEW

**Comment by ramonfm** [comment]
Thanks for the pull request @oc666 -- please take a look at the [Contributing to MongoDB](https://github.com/mongodb/mongo/wiki) section of the wiki for pre-requisites (specially signing the contributor's agreement), which are needed even for tiny changes like this one.

Thanks,
Ramón.

**Comment by oc666** [comment]
@ramonfm I just submitted the agreement.

**Comment by ramonfm** [comment]
@oc666, your github username doesn't come up when I search for it in the list of contributors. I'll check on my end, but you may want to retrace your steps since I don't think this has happened before...

**Comment by oc666** [comment]
@ramonfm 

Hope this will help you...

image

**Comment by ramonfm** [comment]
Thanks @oc666, looks like there's an issue on our end and we're investigating. Your patience is much appreciated.

**Comment by xinxin2015** [comment]
Can I ask how to import the source into the ide,ex vs or clion etc,I want to learn about the sources.Thanks

**Comment by tishakariya** [comment]
Hi Team, 

Want to know if CCLA is required for corporate contribution. Quick response is much appreciated.

Thanks,
Priyanka Kariya

**Comment by ramonfm** [comment]
@tishakariya , all contributions require signing the agreement -- see above for the link.

**Comment by tishakariya** [comment]
Hi @ramonfm,

I have signed a CLA for individual contribution, just wanted to know if there is something for Company (Corporate) contribution. I belong to an organisation and we are planning to contribute to MongoDB Community as a group, so I wanted to know if any separate agreement has to be signed for corporate contribution (CCLA).

Thanks and Regards,
Priyanka Kariya

**Comment by dhatcher42** [comment]
@tishakariya due to the way we track our contributors, we'd prefer to have each person who wishes to contribute to MongoDB sign their own agreement. If this is too onerous to your organization we can have further discussions about this.

**Pull request closed without merging**
