### PR TITLE
SERVER-46011 rename_collection: reduce uuid expression

### PR DESCRIPTION
**Pull request by gaurav1086**
uuid expression reduction

### CODE REVIEW

**Comment by carlchampain** [comment]
Hi,
Thank you for opening up a pull request! 
It looks good, but please make sure to sign our [Contributor Agreement](https://www.mongodb.com/legal/contributor-agreement) as its a requirement for any PRs we accept. We can accept it once the agreement is signed.

**Comment by gaurav1086** [comment]
@carlchampain thanks for the review. signed.

**Comment by Schubes** [comment]
Closed by 56721bbc268e137a20974d9b6d880caaca189541

**Comment by Schubes** [comment]
Thanks for your contribution!

**Comment by gaurav1086** [comment]
@Schubes you are welcome. Has this been merged already ?

**Comment by carlchampain** [comment]
Yes, it has!

**Pull request closed without merging**
