### PR TITLE
Fix typo in repl/README.md

### PR DESCRIPTION
**Pull request by autarch**

### CODE REVIEW

**Review by suenalaba — CHANGES_REQUESTED** [review]
Hi @autarch I think you accidentally keyed in an extra "F" in the word transactions. It should be `transactions`. Could you fix it and re-commit? Cheers!

**Comment by autarch** [comment]
> Hi @autarch I think you accidentally keyed in an extra "F" in the word transactions. It should be `transactions`. Could you fix it and re-commit? Cheers!

Doh! Fixed.

**Review by suenalaba — APPROVED** [review]
Looks good to be merged now.

**Review by cyber-eternal — APPROVED** [review]
LGTM!

**Pull request closed without merging**
