### PR TITLE
SERVER-16720 updated awk regexp to support inline pidFilePath and dbPath...

### PR DESCRIPTION
**Pull request by cammellos**
Updated awk regexp to support inline YAML syntax:
storage.dbPath: ""
processManagement.pidFilePath: ""

to address https://jira.mongodb.org/browse/SERVER-16720

### CODE REVIEW

**Comment by ehershey** [comment]
This lgtm.

**Comment by benety** [comment]
Related to #895

**Comment by benety** [comment]
Hi @cammellos,

Before we merge this pull request, could you please sign the contributor's agreement?

http://www.mongodb.com/contributor

Ben

**Comment by cammellos** [comment]
Signed and rebased to current master

**Comment by benety** [comment]
Sorry for the inconvenience, but we have a different email address in the contributor's agreement (andrea.maria.piana@gmail.com) from the email in the git commit. Would you be able to re-sign the contributor's agreement with your GitHub ID?

**Comment by cammellos** [comment]
I have now signed the agreement with the same email I have used for the commit, sorry for the confusion.

**Comment by benety** [comment]
Hi @cammellos,

This pull request has been merged in https://github.com/mongodb/mongo/commit/e82c06607baf14a00751af681b808c3172bdeff0.

Thank you for contributing to MongoDB!
Ben

**Pull request closed without merging**
