### PR TITLE
[SERVER-32813] Fix typos in config_server_test_fixture.cpp and dpml_error_codes.c

### PR DESCRIPTION
**Pull request by kakts**
## Summary
I found some typos in files as below.

```
src/mongo/s/config_server_test_fixture.cpp
src/third_party/IntelRDFPMathLib20U1/LIBRARY/float128/dpml_error_codes.c
```

reponse  → response

### CODE REVIEW

**Comment by Schubes** [comment]
Hi @kakts,

Sorry for the delay getting back getting back to you. Would you please sign the [contributor agreement](https://www.mongodb.com/legal/contributor-agreement) and open a [SERVER ticket](https://jira.mongodb.org/browse/SERVER/) for this issue, so we can work with you to merge the fix?

Thank you,
Kelsey

**Comment by kakts** [comment]
Hi @Schubes,

I'll sign it and open a SERVER ticket in a few days.

**Comment by kakts** [comment]
Hi, @Schubes 

I've signed the contributor agreement, but in my jira account, I couldn't open a SERVER ticket because of the error as below.

Would you be able to check this?

```
An error occurredHide…
Please try refreshing the page, or contact your administrator / Atlassian Support if the problem continues.
Details
Exception: TypeError: null is not an object (evaluating 'p[1]')
Resource: https://jira.mongodb.org/s/6b46a87482421636799af242c6320639-CDN/3vu41l/72012/863adea011c49e849622efe2626fcfe7/29ca6675f06defcd38d7201b4e8155ed/_/download/contextbatch/js/greenhopper-rapid-non-gadget,gh-rapid,jira.project.sidebar,atl.general,jira.general,com.atlassian.jira.projects.sidebar.init,jira.global,-_super/batch.js?agile_global_admin_condition=true&atlassian.aui.raphael.disabled=true&is-server-instance=true&jag=true&jaguser=true&locale=ja-JP&nps-acknowledged=true&nps-not-opted-out=true&sd_operational=true
Line: 8693
Column: 392
Environment
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.4.7 (KHTML, like Gecko) Version/11.0.2 Safari/604.4.7
```

**Comment by kakts** [comment]
Hi @Schubes 

I've opened new issue.
SERVER-32813   https://jira.mongodb.org/browse/SERVER-32813

**Comment by kakts** [comment]
Hi @MarkAgarunov ,

I'll close this and reopen the same pull request.

Thank you.

**Comment by kakts** [comment]
Hi @MarkAgarunov. I've reopened PR https://github.com/mongodb/mongo/pull/1208

**Pull request closed without merging**
