### PR TITLE
SERVER-48226 Improve TLA+ CI

### PR DESCRIPTION
**Pull request by lemmy**
@ajdavis @will62794 @visualzhou 

* "-workers auto" introduced in https://github.com/tlaplus/tlaplus/commit/4111431a169b96d0b2eb850fd6fb4416cf5af4ff

* OffHeapDiskFPSet: https://lemmster.de/talks/MSc_MarkusAKuppe_1497363471.pdf

* Data that is shared as part of exec stats:
https://github.com/tlaplus/tlaplus/blob/master/tlatools/org.lamport.tlatools/src/util/ExecutionStatisticsCollector.md

### CODE REVIEW

**Comment by ajdavis** [comment]
Thanks! Performance seems about the same with this patch (13m26s in the last successful run, 13m16s when I tried this patch). But I suppose it could be a significant improvement for models with more states.

Have you signed the CLA?: https://www.mongodb.com/legal/contributor-agreement

**Comment by ajdavis** [comment]
Question: if the usage stats service is down, will TLC still run to completion and return exit code 0? We want to avoid spurious test failures.

**Comment by lemmy** [comment]
> Question: if the usage stats service is down, will TLC still run to completion and return exit code 0? We want to avoid spurious test failures.

* Stats do not block TLC and fail silently if e.g. the remote host is down
* OffHeap's properties become noticeable with larger specs and higher core counts
* CLA has been taken care of

**Comment by ajdavis** [comment]
Thanks @lemmy!

**Pull request closed without merging**
