### PR TITLE
Use Boyer-Moore for indexOfBytes and indexOfCP when needle is constant

### PR DESCRIPTION
**Pull request by mattBoros**
https://jira.mongodb.org/browse/SERVER-26752

I doubt I followed the code standards exactly, but I think this will work.

### CODE REVIEW

**Comment by carlchampain** [comment]
Thanks for making this pull request! We just need you to sign our [Contributor's Agreement](https://www.mongodb.com/legal/contributor-agreement) as part of our considering the PR.

**Comment by mattBoros** [comment]
No problem! I just completed and submitted the form.

**Comment by carlchampain** [comment]
Hi @mattBoros! I can't find your name in the [list](https://contributors.corp.mongodb.com/). Can you ensure that the form went through?

**Comment by mattBoros** [comment]
Hi! I received a receipt shortly after signing the form. I realize I used my full first name Matthew instead of Matt. Could this be the issue?

**Comment by carlchampain** [comment]
I still can't find you in the list. I tried your full name and your Github username. Can you try signing the agreement one more time?

**Comment by mattBoros** [comment]
No problem! I just signed the agreement and it sent me a receipt email.

**Comment by carlchampain** [comment]
@mattBoros, we have received your signature. Thank you!

**Pull request closed without merging**
