### PR TITLE
SERVER-5044 stdDev agg opt for standard deviation

### PR DESCRIPTION
**Pull request by msven**
Working standard deviation and variance aggregation operators,
implementing algorithm from
https://gist.github.com/RedBeard0531/1886960.
Unit tests also added.

Added the following aggregation operators:
$stdDev - calculate the standard deviation of the sample
$var    - calculate the variance of the sample
$stdDevPop - calculate the standard deviation of the population
$varPop    - calculate the variance of the population

https://jira.mongodb.org/browse/SERVER-5044

### CODE REVIEW

**Comment by sourcekick** [comment]
+1

**Comment by homam** [comment]
+1

**Comment by nicolaspanel** [comment]
+1

**Comment by ramonfm** [comment]
We are no longer able to merge this pull request, but the good news is that this feature has been scheduled for the current development cycle and it will be part of the next stable release -- please see [SERVER-5044](https://jira.mongodb.org/browse/SERVER-5044) for updates.

Regards,
Ramón.

**Pull request closed without merging**
