### PR TITLE
Fix license wording

### PR DESCRIPTION
**Pull request by Zipdox**
I think this wording more accurately describes the nature of the license.

### CODE REVIEW

**Comment by JamesQuinley** [comment]
I think this goes without saying, no.
This is both inaccurate and very divisive in a place where that isn’t needed.

**Comment by BowDown097** [comment]
LGTM

**Comment by marklovestech** [comment]
I am disappointed that so harmful and hurtful a change would be suggested by a member of the MongoDB community. - Mark Porter, CTO

**Comment by JamesQuinley** [comment]
Is there a way we could lock and close this PR? Since it seems to be purely for harm it has no reason to continue.

**Comment by KaspianDev** [comment]
I agree that mongo license is stupid, that's the main reason I'm not using mongo at all. Just use something normal like GPL (or any subversion of that license).

**Comment by Odyssey346** [comment]
LGTM!

**Comment by arefdsg** [comment]
yes

**Comment by Schubes** [comment]
This PR violates our code of conduct: https://www.mongodb.com/community-code-of-conduct

**Pull request closed without merging**
