### PR TITLE
SERVER-73998 Fix perf.yml

### PR DESCRIPTION
**Pull request by jimoleary**
(cherry picked from commit 638f348aea94c7fa0d26ffcaeb4380430a54d5e6)

### CODE REVIEW

**Comment by jimoleary** [comment]
[patch test](https://spruce.mongodb.com/version/63ecad8b9ccd4e1f221a19ec/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

**Review by jawwadasghar — APPROVED** [review]
LGTM

**Review by dalyd — APPROVED** [review]

**Comment by jimoleary** [comment]
evergreen merge

**Comment by jimoleary** [comment]
evergreen merge

**Comment by jimoleary** [comment]
Attempting to [manually merge](https://spruce.mongodb.com/version/63ecfda10305b942643344e9/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

**Comment by jimoleary** [comment]
merged manually via command line (as this should have been on 10gen/mongo)

**Pull request closed without merging**
